apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: my-node-app
          image: hzdevops52/docker-app:k8s
          ports:
            - containerPort: 80
